apiVersion: apps/v1
kind: Deployment
metadata:
  name: volumes-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: volumes-app
  template:
    metadata:
      labels:
        app: volumes-app
    spec:
      containers:
        - name: node-volumes
          image: badi1298/node-volumes:2
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 256Mi
              cpu: 500m
          env:
            - name: STORY_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: folder
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pvc
